# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: PyPi

steps:
# Use Python version
# Use the specified version of Python from the tool cache, optionally adding it to the PATH
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7' 
    addToPath: true 
    #architecture: 'x64' # Options: x86, x64 (this argument applies only on Windows agents)
- script: |
    python --vertison
    pushd generated
    pip install tox
    pip install -r requirements.txt
    pip install -r test-requirements.txt
    tox
  displayName: Install and Run Tests
- script: |
    pushd generated
    python setup.py sdist
    twine upload -u $PyPi_Username -p $PyPi_Password dist/*
  displayName: 'Run a multi-line script'
  env:
    PyPi_Username: $(PyPi_Username)
    PyPi_Password: $(PyPi_Password)
