# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: PyPi

steps:

- script: |
    pushd generated
    pip install tox
    pip install -r requirements.txt
    pip install -r test-requirements.txt
    tox
  displayName: Install and Run Tests
- script: |
    pushd generated
    python setup.py sdist
    twine upload -u $PyPi_Username -p $PyPi_Password dist/*
  displayName: 'Run a multi-line script'
  env:
    PyPi_Username: $(PyPi_Username)
    PyPi_Password: $(PyPi_Password)
