version: "3"
services:
  generator:
    image: flanagan89/openapi-generator-cli-python:latest
    volumes: 
      - ${PWD}/src:/local
    environment: 
      - PYTHON_POST_PROCESS_FILE=yapf -i
    command: generate -i https://app.amphoradata.com/swagger/v1/swagger.json -g python -o /local/sdk -c local/config.yaml --skip-validate-spec --enable-post-process-file