version: "3"
services:
  generator:
    image: openapitools/openapi-generator-cli
    volumes: 
      - ${PWD}:/local
    command: generate -i https://beta.amphoradata.com/swagger/v1/swagger.json -g python -o /local/generated -c local/config.yaml