# coding: utf-8

"""
    Amphora Data Api

    API for interacting with the Amphora Data platform.  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.create_amphora_all_of import CreateAmphoraAllOf  # noqa: E501
from amphora_api_client.rest import ApiException


class TestCreateAmphoraAllOf(unittest.TestCase):
    """CreateAmphoraAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAmphoraAllOf(self):
        """Test CreateAmphoraAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.create_amphora_all_of.CreateAmphoraAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
