# coding: utf-8
"""
    Amphora Data

                 Connect information in real time with Amphora Data.                          Learn more at https://docs.amphoradata.com  # noqa: E501

    The version of the OpenAPI document: 0.10.8
    Generated by: https://openapi-generator.tech
"""

from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.api.organisations_api import OrganisationsApi  # noqa: E501
from amphora_api_client.rest import ApiException


class TestOrganisationsApi(unittest.TestCase):
    """OrganisationsApi unit test stubs"""
    def setUp(self):
        self.api = amphora_api_client.api.organisations_api.OrganisationsApi(
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_account_get_plan(self):
        """Test case for account_get_plan

        Get's an Organisation's plan information.  # noqa: E501
        """
        pass

    def test_account_read(self):
        """Test case for account_read

        Get's an Organisation's account information.  # noqa: E501
        """
        pass

    def test_organisations_create(self):
        """Test case for organisations_create

        Creates a new Organisation. This will assign the logged in user to the organisation.  # noqa: E501
        """
        pass

    def test_organisations_delete(self):
        """Test case for organisations_delete

        Deletes an organisation.  # noqa: E501
        """
        pass

    def test_organisations_read(self):
        """Test case for organisations_read

        Gets an organisation's details.  # noqa: E501
        """
        pass

    def test_organisations_read_invitations(self):
        """Test case for organisations_read_invitations

        Gets an organisation's invitations.  # noqa: E501
        """
        pass

    def test_organisations_terms_of_use_read(self):
        """Test case for organisations_terms_of_use_read

        Get's a list of an Organisation's Terms of Use.  # noqa: E501
        """
        pass

    def test_organisations_update(self):
        """Test case for organisations_update

        Updates an organisation.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
