# coding: utf-8

"""
    Amphora Data Api

    API for interacting with the Amphora Data platform.  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.event_property import EventProperty  # noqa: E501
from amphora_api_client.rest import ApiException


class TestEventProperty(unittest.TestCase):
    """EventProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventProperty(self):
        """Test EventProperty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.event_property.EventProperty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
