# coding: utf-8

"""
    Amphora Data Api

    API for interacting with the Amphora Data platform.  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.terms_and_conditions import TermsAndConditions  # noqa: E501
from amphora_api_client.rest import ApiException


class TestTermsAndConditions(unittest.TestCase):
    """TermsAndConditions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTermsAndConditions(self):
        """Test TermsAndConditions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.terms_and_conditions.TermsAndConditions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
