# coding: utf-8
"""
    Amphora Data

                 Connect information in real time with Amphora Data.                          Learn more at https://docs.amphoradata.com  # noqa: E501

    The version of the OpenAPI document: 0.10.29
    Generated by: https://openapi-generator.tech
"""

from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.search_response_of_basic_amphora import SearchResponseOfBasicAmphora  # noqa: E501
from amphora_api_client.rest import ApiException


class TestSearchResponseOfBasicAmphora(unittest.TestCase):
    """SearchResponseOfBasicAmphora unit test stubs"""
    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchResponseOfBasicAmphora(self):
        """Test SearchResponseOfBasicAmphora"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.search_response_of_basic_amphora.SearchResponseOfBasicAmphora()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
