# coding: utf-8

"""
    Amphora Data Api

    API for interacting with the Amphora Data platform.  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.update_signal import UpdateSignal  # noqa: E501
from amphora_api_client.rest import ApiException


class TestUpdateSignal(unittest.TestCase):
    """UpdateSignal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSignal(self):
        """Test UpdateSignal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.update_signal.UpdateSignal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
