# coding: utf-8

"""
    Amphora Data Api

    API for interacting with the Amphora Data platform.  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.token_request import TokenRequest  # noqa: E501
from amphora_api_client.rest import ApiException


class TestTokenRequest(unittest.TestCase):
    """TokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenRequest(self):
        """Test TokenRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.token_request.TokenRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
