# coding: utf-8

"""
    Amphora Data Api

    API for interacting with the Amphora Data platform.  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.aggregate_series import AggregateSeries  # noqa: E501
from amphora_api_client.rest import ApiException


class TestAggregateSeries(unittest.TestCase):
    """AggregateSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregateSeries(self):
        """Test AggregateSeries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.aggregate_series.AggregateSeries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
