# coding: utf-8
"""
    Amphora Data

                 Connect information in real time with Amphora Data.                          Learn more at https://docs.amphoradata.com  # noqa: E501

    The version of the OpenAPI document: 0.10.11
    Generated by: https://openapi-generator.tech
"""

from __future__ import absolute_import

import unittest

import amphora_api_client
from amphora_api_client.models.organisation_access_rule_all_of import OrganisationAccessRuleAllOf  # noqa: E501
from amphora_api_client.rest import ApiException


class TestOrganisationAccessRuleAllOf(unittest.TestCase):
    """OrganisationAccessRuleAllOf unit test stubs"""
    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganisationAccessRuleAllOf(self):
        """Test OrganisationAccessRuleAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = amphora_api_client.models.organisation_access_rule_all_of.OrganisationAccessRuleAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
