# coding: utf-8
"""
    Amphora Data

                 Connect information in real time with Amphora Data.                          Learn more at https://docs.amphoradata.com  # noqa: E501

    The version of the OpenAPI document: 0.10.21
    Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

import six

from amphora_api_client.configuration import Configuration


class DetailedAmphoraAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {'purchase_count': 'int', 'signal_count': 'int'}

    attribute_map = {
        'purchase_count': 'purchaseCount',
        'signal_count': 'signalCount'
    }

    def __init__(self,
                 purchase_count=None,
                 signal_count=None,
                 local_vars_configuration=None):  # noqa: E501
        """DetailedAmphoraAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._purchase_count = None
        self._signal_count = None
        self.discriminator = None

        self.purchase_count = purchase_count
        self.signal_count = signal_count

    @property
    def purchase_count(self):
        """Gets the purchase_count of this DetailedAmphoraAllOf.  # noqa: E501


        :return: The purchase_count of this DetailedAmphoraAllOf.  # noqa: E501
        :rtype: int
        """
        return self._purchase_count

    @purchase_count.setter
    def purchase_count(self, purchase_count):
        """Sets the purchase_count of this DetailedAmphoraAllOf.


        :param purchase_count: The purchase_count of this DetailedAmphoraAllOf.  # noqa: E501
        :type: int
        """

        self._purchase_count = purchase_count

    @property
    def signal_count(self):
        """Gets the signal_count of this DetailedAmphoraAllOf.  # noqa: E501


        :return: The signal_count of this DetailedAmphoraAllOf.  # noqa: E501
        :rtype: int
        """
        return self._signal_count

    @signal_count.setter
    def signal_count(self, signal_count):
        """Sets the signal_count of this DetailedAmphoraAllOf.


        :param signal_count: The signal_count of this DetailedAmphoraAllOf.  # noqa: E501
        :type: int
        """

        self._signal_count = signal_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict()
                        if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict") else item,
                        value.items()))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetailedAmphoraAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DetailedAmphoraAllOf):
            return True

        return self.to_dict() != other.to_dict()
